import { NextRequest, NextResponse } from "next/server";
import { DeliveryStatusContractError, parseDeliveryStatusResponse } from "@/lib/delivery-status";
import { authenticatedApiFetch, isUuid, SessionRequiredError } from "@/lib/server-api";
export const dynamic = "force-dynamic";
export async function GET(request: NextRequest, context: { params: Promise<{ orderId: string }> }) {
  const { orderId } = await context.params; if (!isUuid(orderId)) return NextResponse.json({ error: "INVALID_ORDER_ID", message: "The order identifier is invalid." }, { status: 400 });
  try { const upstream = await authenticatedApiFetch(request, `/orders/${orderId}/delivery-status`); if (!upstream.ok) return NextResponse.json({ error: upstream.status === 401 ? "SESSION_EXPIRED" : upstream.status === 403 ? "ORDER_ACCESS_DENIED" : upstream.status === 404 ? "ORDER_NOT_FOUND" : "DELIVERY_STATUS_UNAVAILABLE", message: upstream.status === 401 ? "Your session expired. Sign in again." : upstream.status === 403 ? "This order is not available for this account." : upstream.status === 404 ? "The order could not be found." : "Delivery tracking is temporarily unavailable." }, { status: upstream.status }); const result = parseDeliveryStatusResponse(await upstream.json()); if (result.orderId.toLowerCase() !== orderId.toLowerCase()) throw new DeliveryStatusContractError("Order mismatch"); return NextResponse.json(result, { headers: { "Cache-Control": "no-store" } }); }
  catch (error) { const timeout = error instanceof Error && error.name === "AbortError"; return NextResponse.json({ error: error instanceof SessionRequiredError ? "AUTHENTICATION_REQUIRED" : error instanceof DeliveryStatusContractError ? "DELIVERY_STATUS_CONTRACT_ERROR" : timeout ? "DELIVERY_STATUS_TIMEOUT" : "DELIVERY_STATUS_UNAVAILABLE", message: error instanceof SessionRequiredError ? "Sign in to view delivery tracking." : timeout ? "Delivery tracking took too long to respond." : "Delivery tracking is temporarily unavailable." }, { status: error instanceof SessionRequiredError ? 401 : timeout ? 504 : 502 }); }
}
