export type CustomerOrderItem = { id: string; menuItemId: string; itemName: string; category: string; foodType: string; unitPrice: number; quantity: number; lineTotal: number };
export type CustomerOrder = { id: string; checkoutId: string; kitchenId: string; kitchenName: string; status: string; currency: string; foodSubtotal: number; platformFee: number; taxAmount: number; deliveryFee: number; grandTotal: number; chefResponseNote: string | null; prepTimeMinutes: number | null; deliveryAddress: { recipientName: string; addressLine1: string; addressLine2: string | null; landmark: string | null; areaName: string | null; city: string; state: string; postalCode: string } | null; items: CustomerOrderItem[]; createdAt: string; updatedAt: string };
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i; const STATUSES = new Set(["PAYMENT_PENDING", "PAID", "CHEF_ACCEPTANCE_PENDING", "CHEF_ACCEPTED", "PREPARING", "READY_FOR_PICKUP", "OUT_FOR_DELIVERY", "DELIVERED", "CHEF_REJECTED", "CANCELLED", "REFUND_PENDING", "REFUNDED", "REFUND_FAILED"]);
function text(value: unknown, max = 300): string | null { if (typeof value !== "string") return null; const result = value.trim(); return result && result.length <= max ? result : null; }
function money(value: unknown): number | null { const result = typeof value === "number" ? value : typeof value === "string" ? Number(value) : NaN; return Number.isFinite(result) && result >= 0 && result <= 10_000_000 ? result : null; }
function instant(value: unknown): string | null { return typeof value === "string" && !Number.isNaN(Date.parse(value)) ? value : null; }
function parseItem(value: unknown): CustomerOrderItem | null { if (!value || typeof value !== "object") return null; const raw = value as Record<string, unknown>; const id = text(raw.id, 64); const menuItemId = text(raw.menuItemId, 64); const itemName = text(raw.itemName, 180); const unitPrice = money(raw.unitPrice); const lineTotal = money(raw.lineTotal); const quantity = typeof raw.quantity === "number" && Number.isInteger(raw.quantity) ? raw.quantity : 0; return id && UUID.test(id) && menuItemId && UUID.test(menuItemId) && itemName && unitPrice !== null && lineTotal !== null && quantity >= 1 && quantity <= 100 ? { id, menuItemId, itemName, category: text(raw.category, 80) ?? "Food", foodType: text(raw.foodType, 40) ?? "UNSPECIFIED", unitPrice, quantity, lineTotal } : null; }
function parseAddress(value: unknown): CustomerOrder["deliveryAddress"] { if (!value || typeof value !== "object") return null; const raw = value as Record<string, unknown>; const recipientName = text(raw.recipientName, 160); const addressLine1 = text(raw.addressLine1, 250); const city = text(raw.city, 120); const state = text(raw.state, 120); const postalCode = text(raw.postalCode, 20); return recipientName && addressLine1 && city && state && postalCode ? { recipientName, addressLine1, addressLine2: text(raw.addressLine2, 250), landmark: text(raw.landmark, 160), areaName: text(raw.areaName, 120), city, state, postalCode } : null; }
export function parseCustomerOrder(value: unknown): CustomerOrder | null { if (!value || typeof value !== "object") return null; const raw = value as Record<string, unknown>; const id = text(raw.id, 64); const checkoutId = text(raw.checkoutId, 64); const kitchenId = text(raw.kitchenId, 64); const kitchenName = text(raw.kitchenName, 180); const status = text(raw.status, 40); const currency = text(raw.currency, 3); const createdAt = instant(raw.createdAt); const updatedAt = instant(raw.updatedAt); const items = (Array.isArray(raw.items) ? raw.items : []).slice(0, 100).map(parseItem); const amounts = [raw.foodSubtotal, raw.platformFee, raw.taxAmount, raw.deliveryFee, raw.grandTotal].map(money); if (!id || !UUID.test(id) || !checkoutId || !UUID.test(checkoutId) || !kitchenId || !UUID.test(kitchenId) || !kitchenName || !status || !STATUSES.has(status) || !currency || !createdAt || !updatedAt || items.some((item) => item === null) || amounts.some((amount) => amount === null)) return null; return { id, checkoutId, kitchenId, kitchenName, status, currency: currency.toUpperCase(), foodSubtotal: amounts[0]!, platformFee: amounts[1]!, taxAmount: amounts[2]!, deliveryFee: amounts[3]!, grandTotal: amounts[4]!, chefResponseNote: text(raw.chefResponseNote, 500), prepTimeMinutes: typeof raw.prepTimeMinutes === "number" && Number.isInteger(raw.prepTimeMinutes) ? raw.prepTimeMinutes : null, deliveryAddress: parseAddress(raw.deliveryAddress), items: items as CustomerOrderItem[], createdAt, updatedAt };
}
export function parseCustomerOrders(value: unknown): CustomerOrder[] | null { if (!Array.isArray(value) || value.length > 500) return null; const orders = value.map(parseCustomerOrder); return orders.some((order) => order === null) ? null : orders as CustomerOrder[]; }
export function formatOrderStatus(status: string): string { return status.toLowerCase().split("_").map((part) => part[0]?.toUpperCase() + part.slice(1)).join(" "); }
