-- UUIDs are generated by the Java service. Keep this migration extension-free so it runs
-- on Azure Database for PostgreSQL without changing the azure.extensions allow list.
CREATE SCHEMA IF NOT EXISTS delivery_schema;

CREATE TABLE IF NOT EXISTS delivery_schema.delivery_provider (
    provider_id            VARCHAR(80) PRIMARY KEY,
    display_name           VARCHAR(160) NOT NULL,
    adapter_type           VARCHAR(120) NOT NULL,
    is_active              BOOLEAN NOT NULL DEFAULT FALSE,
    service_areas          JSONB NOT NULL DEFAULT '[]'::jsonb,
    capabilities           JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_delivery_provider_id_lower CHECK (provider_id = lower(provider_id)),
    CONSTRAINT ck_delivery_provider_service_areas_array CHECK (jsonb_typeof(service_areas) = 'array'),
    CONSTRAINT ck_delivery_provider_capabilities_object CHECK (jsonb_typeof(capabilities) = 'object')
);

CREATE INDEX IF NOT EXISTS ix_delivery_provider_active
    ON delivery_schema.delivery_provider (is_active, updated_at DESC);

CREATE TABLE IF NOT EXISTS delivery_schema.delivery_partner_bandit_state (
    provider_id            VARCHAR(80) PRIMARY KEY REFERENCES delivery_schema.delivery_provider(provider_id),
    alpha                  DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    beta                   DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_delivery_bandit_alpha CHECK (alpha > 0),
    CONSTRAINT ck_delivery_bandit_beta CHECK (beta > 0)
);

CREATE TABLE IF NOT EXISTS delivery_schema.delivery_partner_rolling_state (
    provider_id            VARCHAR(80) PRIMARY KEY REFERENCES delivery_schema.delivery_provider(provider_id),
    stored_avg             DOUBLE PRECISION NOT NULL,
    stored_weight          DOUBLE PRECISION NOT NULL DEFAULT 0,
    stored_breakdown       JSONB NOT NULL DEFAULT '{}'::jsonb,
    lifetime_order_count   BIGINT NOT NULL DEFAULT 0,
    last_folded_at         TIMESTAMPTZ,
    CONSTRAINT ck_delivery_rolling_avg CHECK (stored_avg BETWEEN 0 AND 100),
    CONSTRAINT ck_delivery_rolling_weight CHECK (stored_weight >= 0),
    CONSTRAINT ck_delivery_rolling_lifetime_count CHECK (lifetime_order_count >= 0)
);

CREATE TABLE IF NOT EXISTS delivery_schema.delivery_partner_daily_archive (
    provider_id            VARCHAR(80) NOT NULL REFERENCES delivery_schema.delivery_provider(provider_id),
    archive_date           DATE NOT NULL,
    day_avg_score          DOUBLE PRECISION NOT NULL,
    day_breakdown          JSONB NOT NULL DEFAULT '{}'::jsonb,
    day_order_count        BIGINT NOT NULL,
    stored_avg_after_fold  DOUBLE PRECISION NOT NULL,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (provider_id, archive_date),
    CONSTRAINT ck_delivery_archive_avg CHECK (day_avg_score BETWEEN 0 AND 100),
    CONSTRAINT ck_delivery_archive_stored_avg CHECK (stored_avg_after_fold BETWEEN 0 AND 100),
    CONSTRAINT ck_delivery_archive_count CHECK (day_order_count > 0)
);

CREATE TABLE IF NOT EXISTS delivery_schema.delivery_assignment (
    id                     UUID PRIMARY KEY,
    chef_sub_order_id      UUID NOT NULL UNIQUE,
    order_id               UUID NOT NULL,
    strategy               VARCHAR(30) NOT NULL,
    status                 VARCHAR(30) NOT NULL,
    scoring_version        VARCHAR(200) NOT NULL,
    selected_candidate_id  UUID,
    selected_provider_id   VARCHAR(80) REFERENCES delivery_schema.delivery_provider(provider_id),
    selected_agent_id      VARCHAR(160),
    request_context        JSONB NOT NULL,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_delivery_assignment_strategy CHECK (strategy IN ('GREEDY', 'STOCHASTIC')),
    CONSTRAINT ck_delivery_assignment_status CHECK (status IN ('RANKED', 'ASSIGNED', 'EXHAUSTED', 'CANCELLED'))
);

CREATE INDEX IF NOT EXISTS ix_delivery_assignment_order
    ON delivery_schema.delivery_assignment (order_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_delivery_assignment_provider
    ON delivery_schema.delivery_assignment (selected_provider_id, created_at DESC);

CREATE TABLE IF NOT EXISTS delivery_schema.delivery_assignment_candidate (
    id                              UUID PRIMARY KEY,
    assignment_id                   UUID NOT NULL REFERENCES delivery_schema.delivery_assignment(id) ON DELETE CASCADE,
    provider_id                     VARCHAR(80) NOT NULL REFERENCES delivery_schema.delivery_provider(provider_id),
    provider_quote_id               VARCHAR(200),
    agent_id                        VARCHAR(160),
    candidate_rank                  INTEGER NOT NULL,
    pickup_distance_km              DOUBLE PRECISION,
    pickup_eta_minutes              DOUBLE PRECISION,
    quoted_cost                     NUMERIC(12,2),
    currency                        VARCHAR(3),
    predicted_success_probability   DOUBLE PRECISION NOT NULL,
    combined_score                  DOUBLE PRECISION NOT NULL,
    live_avg                        DOUBLE PRECISION,
    stored_avg                      DOUBLE PRECISION NOT NULL,
    momentum                        VARCHAR(30) NOT NULL,
    exploration_sample              DOUBLE PRECISION NOT NULL,
    provider_quality_score          DOUBLE PRECISION NOT NULL,
    proximity_score                 DOUBLE PRECISION NOT NULL,
    final_score                     DOUBLE PRECISION NOT NULL,
    status                          VARCHAR(30) NOT NULL,
    provider_metadata               JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at                      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (assignment_id, candidate_rank),
    CONSTRAINT ck_delivery_candidate_rank CHECK (candidate_rank > 0),
    CONSTRAINT ck_delivery_candidate_probability CHECK (predicted_success_probability BETWEEN 0 AND 1),
    CONSTRAINT ck_delivery_candidate_combined CHECK (combined_score BETWEEN 0 AND 100),
    CONSTRAINT ck_delivery_candidate_stored CHECK (stored_avg BETWEEN 0 AND 100),
    CONSTRAINT ck_delivery_candidate_exploration CHECK (exploration_sample BETWEEN 0 AND 1),
    CONSTRAINT ck_delivery_candidate_quality CHECK (provider_quality_score BETWEEN 0 AND 100),
    CONSTRAINT ck_delivery_candidate_proximity CHECK (proximity_score BETWEEN 0 AND 100),
    CONSTRAINT ck_delivery_candidate_final CHECK (final_score BETWEEN 0 AND 100),
    CONSTRAINT ck_delivery_candidate_momentum CHECK (momentum IN ('IMPROVING', 'DECLINING', 'STABLE', 'INSUFFICIENT_DATA')),
    CONSTRAINT ck_delivery_candidate_status CHECK (status IN ('RANKED', 'SELECTED', 'ATTEMPTED', 'ACCEPTED', 'DECLINED', 'FAILED', 'SKIPPED'))
);

CREATE INDEX IF NOT EXISTS ix_delivery_assignment_candidate_assignment
    ON delivery_schema.delivery_assignment_candidate (assignment_id, candidate_rank);
CREATE INDEX IF NOT EXISTS ix_delivery_assignment_candidate_provider
    ON delivery_schema.delivery_assignment_candidate (provider_id, created_at DESC);

CREATE TABLE IF NOT EXISTS delivery_schema.delivery_outcome_receipt (
    delivery_id            UUID PRIMARY KEY,
    chef_sub_order_id      UUID NOT NULL UNIQUE,
    order_id               UUID NOT NULL,
    provider_id            VARCHAR(80) NOT NULL REFERENCES delivery_schema.delivery_provider(provider_id),
    composite_score        DOUBLE PRECISION NOT NULL,
    breakdown              JSONB NOT NULL,
    occurred_at            TIMESTAMPTZ NOT NULL,
    received_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_delivery_outcome_receipt_score CHECK (composite_score BETWEEN 0 AND 100)
);

CREATE INDEX IF NOT EXISTS ix_delivery_outcome_receipt_provider_time
    ON delivery_schema.delivery_outcome_receipt (provider_id, occurred_at DESC);

CREATE TABLE IF NOT EXISTS delivery_schema.delivery_score_hot (
    delivery_id            UUID PRIMARY KEY,
    chef_sub_order_id      UUID NOT NULL UNIQUE,
    order_id               UUID NOT NULL,
    provider_id            VARCHAR(80) NOT NULL REFERENCES delivery_schema.delivery_provider(provider_id),
    composite_score        DOUBLE PRECISION NOT NULL,
    status                 VARCHAR(30) NOT NULL,
    distance_km            DOUBLE PRECISION NOT NULL,
    area                   VARCHAR(160) NOT NULL,
    order_hour             SMALLINT NOT NULL,
    day_of_week            SMALLINT NOT NULL,
    occurred_at            TIMESTAMPTZ NOT NULL,
    breakdown              JSONB NOT NULL,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_delivery_score_composite CHECK (composite_score BETWEEN 0 AND 100),
    CONSTRAINT ck_delivery_score_status CHECK (status IN ('DELIVERED', 'CANCELLED', 'FAILED')),
    CONSTRAINT ck_delivery_score_hour CHECK (order_hour BETWEEN 0 AND 23),
    CONSTRAINT ck_delivery_score_dow CHECK (day_of_week BETWEEN 0 AND 6)
);

CREATE INDEX IF NOT EXISTS ix_delivery_score_hot_provider_time
    ON delivery_schema.delivery_score_hot (provider_id, occurred_at);
CREATE INDEX IF NOT EXISTS ix_delivery_score_hot_occurred_at
    ON delivery_schema.delivery_score_hot (occurred_at);

CREATE TABLE IF NOT EXISTS delivery_schema.delivery_command (
    id                     UUID PRIMARY KEY,
    chef_sub_order_id      UUID NOT NULL UNIQUE,
    order_id               UUID NOT NULL,
    command_type           VARCHAR(30) NOT NULL,
    status                 VARCHAR(30) NOT NULL DEFAULT 'SCHEDULED',
    ready_at               TIMESTAMPTZ,
    dispatch_at            TIMESTAMPTZ NOT NULL,
    attempt_count          INTEGER NOT NULL DEFAULT 0,
    idempotency_key        VARCHAR(200) NOT NULL UNIQUE,
    payload                JSONB NOT NULL,
    last_error             TEXT,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_delivery_command_type CHECK (command_type IN ('QUOTE_AND_CREATE', 'CANCEL', 'TRACK')),
    CONSTRAINT ck_delivery_command_status CHECK (status IN ('SCHEDULED', 'PROCESSING', 'COMPLETED', 'FAILED', 'DEAD_LETTER')),
    CONSTRAINT ck_delivery_command_attempts CHECK (attempt_count >= 0)
);

CREATE INDEX IF NOT EXISTS ix_delivery_command_due
    ON delivery_schema.delivery_command (status, dispatch_at);

CREATE TABLE IF NOT EXISTS delivery_schema.delivery_job (
    id                     UUID PRIMARY KEY,
    chef_sub_order_id      UUID NOT NULL UNIQUE,
    order_id               UUID NOT NULL,
    assignment_id          UUID REFERENCES delivery_schema.delivery_assignment(id),
    provider_id            VARCHAR(80) NOT NULL REFERENCES delivery_schema.delivery_provider(provider_id),
    provider_delivery_id   VARCHAR(200),
    provider_quote_id      VARCHAR(200),
    assigned_agent_id      VARCHAR(160),
    status                 VARCHAR(40) NOT NULL,
    tracking_url           TEXT,
    quote_snapshot         JSONB NOT NULL DEFAULT '[]'::jsonb,
    booked_at              TIMESTAMPTZ,
    picked_up_at           TIMESTAMPTZ,
    delivered_at           TIMESTAMPTZ,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (provider_id, provider_delivery_id)
);

CREATE INDEX IF NOT EXISTS ix_delivery_job_order
    ON delivery_schema.delivery_job (order_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_delivery_job_status
    ON delivery_schema.delivery_job (status, updated_at DESC);

CREATE TABLE IF NOT EXISTS delivery_schema.delivery_event (
    id                     UUID PRIMARY KEY,
    delivery_job_id        UUID NOT NULL REFERENCES delivery_schema.delivery_job(id),
    provider_id            VARCHAR(80) NOT NULL,
    provider_event_id      VARCHAR(200),
    event_type             VARCHAR(120) NOT NULL,
    normalized_status      VARCHAR(40),
    payload                JSONB NOT NULL,
    occurred_at            TIMESTAMPTZ NOT NULL,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (provider_id, provider_event_id)
);

CREATE INDEX IF NOT EXISTS ix_delivery_event_job_time
    ON delivery_schema.delivery_event (delivery_job_id, occurred_at);

CREATE TABLE IF NOT EXISTS delivery_schema.delivery_webhook_inbox (
    id                     UUID PRIMARY KEY,
    provider_id            VARCHAR(80) NOT NULL,
    provider_event_id      VARCHAR(200),
    signature_hash         VARCHAR(300),
    processing_status      VARCHAR(30) NOT NULL DEFAULT 'RECEIVED',
    raw_payload            JSONB NOT NULL,
    error_message          TEXT,
    received_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    processed_at           TIMESTAMPTZ,
    UNIQUE (provider_id, provider_event_id),
    CONSTRAINT ck_delivery_webhook_status CHECK (processing_status IN ('RECEIVED', 'PROCESSING', 'PROCESSED', 'DUPLICATE', 'REJECTED', 'FAILED'))
);

CREATE INDEX IF NOT EXISTS ix_delivery_webhook_inbox_status
    ON delivery_schema.delivery_webhook_inbox (processing_status, received_at);

CREATE TABLE IF NOT EXISTS delivery_schema.delivery_outbox (
    id                     UUID PRIMARY KEY,
    event_type             VARCHAR(120) NOT NULL,
    aggregate_type         VARCHAR(80) NOT NULL,
    aggregate_id           UUID NOT NULL,
    correlation_id         UUID,
    payload                JSONB NOT NULL,
    status                 VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    attempt_count          INTEGER NOT NULL DEFAULT 0,
    next_attempt_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    published_at           TIMESTAMPTZ,
    last_error             TEXT,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_delivery_outbox_status CHECK (status IN ('PENDING', 'PROCESSING', 'PUBLISHED', 'FAILED', 'DEAD_LETTER')),
    CONSTRAINT ck_delivery_outbox_attempts CHECK (attempt_count >= 0)
);

CREATE INDEX IF NOT EXISTS ix_delivery_outbox_due
    ON delivery_schema.delivery_outbox (status, next_attempt_at);
